name: Super-Linter
on: push

jobs:
  super-lint:
    name: Link code base
    runs-on: ubuntu-latest
    steps:
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GIHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
